### ISSUE TITLE
Getting error after upload a file inside a folder

### ISSUE THREAD

**Issue by xaotix** [prasathmani/tinyfilemanager#1000]
PHP Deprecated:  ctype_digit(): Argument of type int will be interpreted as string in the future in D:\web\localuser\dlm\www\drive\index.php on line 2589

PHP Version 8.2.1
Windows NT WEB22F35 10.0 build 17763 (Windows Server 2019) i586

Lang: en

**Comment by ner00** [comment]
Technically, this is a warning and not an error. And it should only show if Error Reporting is enabled in the settings, otherwise it shouldn't have been shown.

As of PHP 8.1.0, `$size` should be cast as string: https://github.com/prasathmani/tinyfilemanager/blob/6a6eb8abecef523aafda0e9aa71f94f231128222/tinyfilemanager.php#L2589
should be something like:
```php
if (ctype_digit(strval($size))) {
```

**Comment by KrinalPatel889** [comment]
@ner00 Do you have any discord account or Telegram?

Sorry not found any other way to contact you!

I'm not sure if you still have interest in the topic or lost but PEpasspass doesn't work with Windows 11 24H2 local account.

I hope you can update it again. And please provide any other way for communication as reboot.pro is down there is no way I could contact you.

Looking forward to hear from you!
