### ISSUE TITLE
Unable to log in after setting up LetsEncrypt

### ISSUE THREAD

**Issue by DelKatey** [prasathmani/tinyfilemanager#155]
After setting up the server to rewrite all requests to HTTPS, upon logging in, the user gets taken to https://example.com/?p=, when the file manager itself is located at https://example.com/filemanager/index.php.

**Comment by prasathmani** [comment]
try with absolute path in `$root_path`

**Comment by prasathmani** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest version
