### ISSUE TITLE
Button View File not Working

### ISSUE THREAD

**Issue by zaenalalamsyah1** [prasathmani/tinyfilemanager#159]
Why button view not working ? if i  open pdf format or image is blank, and show my coding in directory.

Thanks

**Comment by prasathmani** [comment]
@zaenalalamsyah1 , you mean quick view does not work? Did you try with normal view? 
some times large file take time.

**Comment by prasathmani** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest version
