### ISSUE TITLE
Unzip fails

### ISSUE THREAD

**Issue by AndreFabris** [prasathmani/tinyfilemanager#160]
Hi, great app. I have two zip files 500 and 800MB, and unzipping fails immediately with error: Archive not unpacked
Smaller files work fine

The issue is with highly compressed zip files, normal compression works fine

**Comment by prasathmani** [comment]
I tried with 2GB zip files, it is working, try to increase php execution time and memory limit and check.

**Comment by AndreFabris** [comment]
I have no problem with 2gb files. It is high compression zip files that fail. Normal compression works fine

**Comment by prasathmani** [comment]
Oh, than even I don't have any idea.

**Comment by prasathmani** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest version
