### ISSUE TITLE
Demo doesn't work with Brave Browser

### ISSUE THREAD

**Issue by ikwyl6** [prasathmani/tinyfilemanager#191]
I've tried both the admin and user usernames on your demo but it just reloads the same login page. I tried it on my local server and started having the same issue.. Is there a browser check you do that limits using tfm?

**Comment by prasathmani** [comment]
No browser limitation, It should work in all the browsers. try with different browser

**Comment by nk932714** [comment]
yes demo is not working with the browsers who are using ad blocking plugins.


In Mozilla Firefox if you are using  **uBlock Origin** then demo link will show a blank page.
Might be this is the same case with Brave Browser because it also have built in ad blocker. 

![image](https://user-images.githubusercontent.com/29853208/61784569-8f247700-ae27-11e9-9f37-403a7e6a89c0.png)

Solution :- Disable uBlock origin.
or if you are using Brave browser then disable adblock option if available in browser.

else try this link [https://tinyfilemanager.eu-gb.mybluemix.net/Demo/index.php](https://tinyfilemanager.eu-gb.mybluemix.net/Demo/index.php)
