### ISSUE TITLE
Server responded with 0 code

### ISSUE THREAD

**Issue by jcn50** [prasathmani/tinyfilemanager#229]
I am getting this JS error:
`Server responded with 0 code`
when trying to upload some file. The error is not descriptive at all.

**Comment by prasathmani** [comment]
Change the maximum upload file size in PHP configuration

**Comment by jcn50** [comment]
I did~~still it gave me the error. The error is too generic to know what is really going on. If the upload could be made in chunks regardless of the upload max size that would be great (like the cPanel/WHM uploader).

**Comment by dvjantry60** [comment]
> Cambiar el tamaño máximo del archivo de carga en la configuración de PHP PO CTM

**Comment by awoywood** [comment]
I had the same problem. The message is shown by the Dropzone javascript library, which is included in Tiny, so the message cannot be changed. 
In my case, the problem was that I configured an $http_host in a subdomain (www.) and I was using the script in the domain. Also check that you are using https to avoid problems.

**Comment by oleksandr-omelchenko** [comment]
I'm using HTTPS on my website, but dropzone.js tries to upload file with HTTP.
![Screenshot_1](https://user-images.githubusercontent.com/18086156/167138375-cde13cde-b31e-445d-98f5-8833387ae819.jpg)
