### ISSUE TITLE
Anyone can see any file without login

### ISSUE THREAD

**Issue by zkrx** [prasathmani/tinyfilemanager#255]
I don't understand. It seems that if you guess the file path, you can access any file without logging in, even with auth enabled, rendering it useless.

For example, type in the address bar:
https://your.host/path/to/picture1.jpg

and you will get access to picture1.jpg, without having to login.

What am I missing? People really want to expose all their data to the outside world?

**Comment by prasathmani** [comment]
It is just file manager tool to manage files, it not security tool to protect files in the server, anyone can access files from a server if they know the file path, nothing can do with tinyfilemanager and tinyfilemanager is fully private until you will share with the outside world. if you know better, feel free to contribute @zkrx .

**Comment by zkrx** [comment]
I feel like you should at least warn users in the documentation. You're advertising a false sense of security with the authentication feature. I'm sure that many people use this application to access their files from the outside, perhaps without knowing that their data is public.

Besides, while I'm no PHP expert, I don't believe that this has nothing to do with tinyfilemanager. You could (and should IMO) definitely handle this case in the PHP code.

Again, I hardly do any PHP. But one could start by checking the $_SESSION token before giving access to any file. I'm sure that there's plenty of information available on the topic.

**Comment by andrewlytvyn** [comment]
Without having login and knowing path to file you only have read acces

**Comment by EV-soft** [comment]
Suggested Note:
"Please be aware that the TinyFile Manager access system only protects access to the application. To block files from public access, do so in the web server's file system! (.htaccess)"

**Comment by joglomedia** [comment]
move your storage path outside the public_html (usually)

**Comment by etnx** [comment]
> move your storage path outside the public_html (usually)

To be more specific, you need to modify this line like this (line 72):

`$root_path = '/my-secret-folder/not-in-public_html/';`

Note: Root url for links in file manager won't work anymore. Maybe you should remove these from the front-end (line 1799 and 1853):

`<a title="<?php echo lng('DirectLink')?>" href="<?php echo fm_enc(FM_ROOT_URL . (FM_PATH != '' ? '/' . FM_PATH : '') . '/' . $f . '/') ?>" target="_blank"><i class="fa fa-link" aria-hidden="true"></i></a>`
...
`<a title="<?php echo lng('DirectLink') ?>" href="<?php echo fm_enc(FM_ROOT_URL . (FM_PATH != '' ? '/' . FM_PATH : '') . '/' . $f) ?>" target="_blank"><i class="fa fa-link"></i></a>`

**Comment by alecos71** [comment]
If you need to **protect** files and folders into your web site and you can use **Apache Web Server**, (php is mandatory) I suggest you my application script: https://www.alecos.it/download_eng.php#Apache-HT

Usage is simple: **upload** into your website folder and then **run** it into your web browser.

Don't use special characters since **Apache** cannot store them into **htpasswd**. But you can think a very complex user and password.

**_Merry Christmas and Happy New Year!_**

**Comment by piratetub** [comment]
Shouldn't this issue be closed?

**Comment by ririko5834** [comment]
Hello, does anyone know of a more secure alternative to TinyFileManager? I thought that you can't access files without logging in, it should be definitely protected so that only if the session cookie is valid you can browse the file. Then there should be an option share where you could generate a sharing link for a file or a folder and with that link also people who are not logged in could view/download that single folder/file. It shouldn't be possible to access file by guessing the path, its not secure.
