### ISSUE TITLE
problem uploading files

### ISSUE THREAD

**Issue by qwwwest** [prasathmani/tinyfilemanager#281]
tinyfilemanager uploading works well except when using it embedded...
`define('FM_EMBED', true);`
then the uploading fails while saying everything was fine...

**Comment by prasathmani** [comment]
#233 
check folder has write permission

**Comment by deivh** [comment]
I'm on Windows. 
If I use TinyFileManager without embedding it I can upload in that folder. If I embed TinyFileManager It does not work anymore...

**Comment by deivh** [comment]
@prasathmani !
I have found out why uploading fail in my case... 
i use a .htaccess file to redirect virtual URL to my index.php.
My index.php display TinyFileManager for the URL 'admin/fm'.
now... the generated html by  TinyFileManager point to my index.php instead of 'admin/fm'
so my index.html fail to load TinyFileManager...
I managed to solve this problem by changing TinyFileManager @ line 1083 :
```
<?php echo htmlspecialchars($_SERVER["PHP_SELF"]) . '?p=' . fm_enc(FM_PATH) ?>
<? echo htmlspecialchars(FM_SELF_URL) . '?p=' . fm_enc(FM_PATH) ?>
```
and i use : 
`define('FM_SELF_URL', dirname($_SERVER['PHP_SELF']) . '/admin/fm');
`
Is it a bug or a feature ? 
Thanks for this great program :)

**Comment by prasathmani** [comment]
@deivh great! 
you can manage the path and URL by configuration,
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'/admin/fm';
$root_url = '/admin/fm';
```

**Comment by deivh** [comment]
@prasathmani 
I use TinyFileManager for my CMS to handle media files... 
'/admin/fm' is not a real folder just a URL
if i try to configure this way i get : 
Root path "C:/laragon/www/mempad/admin/fm" not found!

**Comment by prasathmani** [comment]
okay, if you want to change the only URL use `$root_url`. or your approach `FM_SELF_URL` also fine

**Comment by deivh** [comment]
if I change only` $root_url` then it generates URL  like this : 
http://localhost/mempad/admin/fm/dev.jpg (which does not work)
my real "root folder" for uploading files is '/var/www/mempad/media/'
("http://localhost/mempad/media")
I think there is a problem using TinyFileManager with htaccess if we dont use my workaround
@ line 1083
