### ISSUE TITLE
找不到文件（导致无法下载文件、修改文件名称）

### ISSUE THREAD

**Issue by ghost** [prasathmani/tinyfilemanager#412]
('VERSION', '2.4.3')
有时无法对文件进行操作、提示找不到文件。看了下你的代码。
初步定位是我的文件名开头存在空格，导致无法对获取文件的url  。导致无法文件进行命名、移动等操作。
空格导致的BUG。
这是个比较严重的问题、希望能够尽快解决

英语不好，多多包含。

**Comment by GonistLelatel** [comment]
('VERSION', '2.4.3')
Sometimes the file cannot be operated and the file cannot be found. Take a look at your code.
The preliminary positioning is that there is a space at the beginning of my file name, which makes it impossible to obtain the file url. As a result, the file cannot be named or moved.
BUG caused by spaces.
This is a serious problem, I hope it can be resolved as soon as possible

English is not good, so include a lot.

**Comment by GonistLelatel** [comment]
Actual
* cant create file " file.txt" with "New item" button -> created a "file.txt" but not " file.txt"
* create file with space manually (windows cmd) `ren "hello.txt" " hello.txt"`
   * filemanager do not display a " hello.txt" at list -> displays as "hello.txt"
* cant edit the file with leading spaces -> file not saved
