### ISSUE TITLE
any plan for drag/drop file for upload in files list area?

### ISSUE THREAD

**Issue by tassanya** [prasathmani/tinyfilemanager#426]
Thanks for your tinyfilemanager 
Can I ask for upload file feature that We can just drag and drop file into files list area so we don't need to click on upload menu

* I gave to college for test tinyfilemanager ,as first use they all do the same thing to tried by drag the file on their desktop and try to throw into files area in tinyfilemanager

**Comment by prasathmani** [comment]
It is already available in the application, you can drag and drop the files to upload.
![image](https://user-images.githubusercontent.com/11345598/92751607-c1839180-f3a5-11ea-926a-8087cc949943.png)

**Comment by noomdatayoung** [comment]
Thanks for answered,may be I wrote not cleared 
I mean just drag file into files list area(<div id="wrapper" class="container-fluid">) 
,Don't need to go click on upload menu on upper bar
right now if I drag file in this files list area without click upload browser will open the file instead of upload

![Capture1](https://user-images.githubusercontent.com/6849553/92886870-3e624a00-f43e-11ea-9ea9-f22df2a3a564.PNG)

![Capture](https://user-images.githubusercontent.com/6849553/92885916-67cea600-f43d-11ea-976e-a86fab1cb804.PNG)

**Comment by prasathmani** [comment]
As of now tinyfilemanger doesn't support drag and drop the file in the listing area.
