### ISSUE TITLE
tinyfilemanager.php contain malware

### ISSUE THREAD

**Issue by annash-zm** [prasathmani/tinyfilemanager#581]
how to fix tinyfilemanager.php file contain malware so i can't upload file or the file is deleted?

**Comment by 17500mph** [comment]
There's references to this here and there and it's a vulnerability for code injection, not an issue of malware contained within Tiny File Manager. 

As best I can tell is that the vulnerability has been fixed as well. 

Whatever scan/check is being referenced elsewhere here is ambiguous otherwise. 

Can this be confirmed and this issue marked appropriately?

**Comment by 17500mph** [comment]
The ambiguous reference I'm citing is #578
('SiteLock' - appears to be some for pay service, a not openly accessible FUD inducing bait)

**Comment by saeed74** [comment]
I used [https://www.virustotal.com/](https://www.virustotal.com/) to check the file and it also showing malware detection: VUL.Webshell

**Comment by precamp-io** [comment]
cpanel wont let me upload the file because it says it has malware

**Comment by FransW5** [comment]
Solution for cPanel:

Open tinyfilemanager.php in a text editor And

Replace All:
`fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));
`
With:
`$FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));`
