### ISSUE TITLE
Sorting by date time still doesn't work

### ISSUE THREAD

**Issue by eugeniob90** [prasathmani/tinyfilemanager#704]
See the document attached.
![tinyfilemanagerissue](https://user-images.githubusercontent.com/98108689/150370515-3efd59cf-cfab-4c18-9b5f-01f9e95181e0.png)

**Comment by Sundwalltanner** [comment]
I believe this is due to the DataTables plug-in basing whether it uses the text within the `<td>` element or the `data-sort` attribute of that element on the first row in the table. I think this is fine as long as you're at the root, but if you're anywhere deeper than that where the first row of the table is a back button and a bunch of empty cells, those empty cells don't have `data-sort` attributes, so the DataTables plug-in ends up using the text within each `<td>` element and completely ignores `data-sort`.

This is the same problem causing issue #485.
