### ISSUE TITLE
Some Hosting do not allow this tinyfilemanager

### ISSUE THREAD

**Issue by azharul787** [prasathmani/tinyfilemanager#999]
I am using this tinyfilemanager to manage file in cPanel. But some hosting do not allowing this file when I upload this file in cPanel hosting then it has been deleting suddenly. What can I do now please help me. and why this is happening, when I contacting to them they are saying this file is acting as a malicious type so that the hosting security system detect this take action.

**Comment by smalos** [comment]
Check out 
https://github.com/prasathmani/tinyfilemanager/issues/995

**Comment by prasathmani** [comment]
https://github.com/prasathmani/tinyfilemanager/issues/759
https://github.com/prasathmani/tinyfilemanager/issues/581

**Comment by ner00** [comment]
I think this is bound to happen no matter how much stuff is tweaked; it's a file manager and hosting companies do not like custom file managers which may be used by hackers to access, edit or download sensitive data. This must be resolved directly with the hosting company because eventually a new malware signature will blacklist TFM again. 

You either have access to the hosting service and a whitelist for TFM or take it up with the hosting admins. 

This issue should be closed.
